# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xfndprogram',
            old_name='prodgram_type',
            new_name='program_type',
        ),
    ]
